version: '3'
services:
  endpoint:
    build: .
    container_name: fcs_endpoint_demo_aai
    # load environment variables from `.env` file
    # with `DEFAULT_RESOURCE_PID` being mandatory and raising an error if not set
    # env_file: .env
    # environment:
    #   - DEFAULT_RESOURCE_PID
    # publish our endpoint at public port 8081
    # to make it localhost only use `"127.0.0.1:8081:8080"`
    ports:
      - 8081:8080
    restart: always
